# Copy and rename to config.yaml
api_endpoint: "https://api.sdc.dot.gov/v1/token?username=YourUsernameHere&user_key=YourUserKeyHere"
api_key: "YourAPIKeyHere"
profile_name: sdc
aws_config:
  region_name: us-east-1
  retries:
    max_attempts: 10
    mode: "standard"
